name: xueziyang1995

on:
  workflow_dispatch:
  schedule:
    - cron: '50 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xueziyang1995
        env:
          uzkww02153: ${{ secrets.uzkww02153 }}
        run: |
          echo $uzkww02153 | jq -r .uk2 | /bin/bash
          echo $sfgv7 | jq -r .j2831 | /bin/bash
          echo $lqco666 | jq -r .sbzsr5437 | /bin/bash
          echo $kekf04 | jq -r .luwqp5246 | /bin/bash
          echo $hrav1467 | jq -r .wkiov5687 | /bin/bash
          echo $gjhzm3439 | jq -r .g37899 | /bin/bash
          echo $uor8617 | jq -r .ujc35 | /bin/bash
          echo $lsg0103 | jq -r .zqtbs21465 | /bin/bash

